Error: Invalid src prop (https://opensourcecodes.vercel.app/favicon.png) on `next/image`, hostname "opensourcecodes.vercel.app" is not configured under images in your `next.config.js` See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
Fix this error by using normal <img component instead of NextImage or Image